os: osx
language: cpp

compiler:
    - clang

install:
  - .ci/download-homebrew

script:
  - conan config install https://github.com/includeos/conan_config.git
  - conan create . includeos/latest -pr apple-clang-10-macos-toolchain
  - VERSION=$(conan inspect -a version . | cut -d " " -f 2)
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      conan upload --all diskbuilder/$VERSION@includeos/latest -r includeos
    fi
    if [ -n "$TRAVIS_TAG" ]; then
      conan copy --all diskbuilder/$VERSION@includeos/latest includeos/stable
      conan upload --all diskbuilder/$VERSION@includeos/latest -r includeos
      conan upload --all diskbuilder/$VERSION@includeos/stable -r includeos
    fi
