os: osx
language: cpp

compiler:
    - clang

install:
  - git clone https://github.com/staiyeba/travisci-cache.git
  - tar zxf travisci-cache/homebrew-cache.tar.gz --directory /usr/local/Cellar conan cmake python
  - brew link conan python3 python


script:
  - conan config install https://github.com/includeos/conan_config.git
  - conan create . includeos/latest -pr apple-clang-10-macos-toolchain
  - VERSION=$(conan inspect -a version . | cut -d " " -f 2)
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      conan search diskbuilder
    fi
    if [ -n "$TRAVIS_TAG" ]; then
      conan search diskbuilder
    fi
